config/routes.rb
Rails.application.routes.draw do
  get '/list', to: 'flats#list'
  get '/single/:id', to: 'flats#single', as: :single
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
# require "open-uri" nao preisamos disso aqui

class FlatsController < ApplicationController
  def list
    get_flats
  end

  def single
    get_flats
    # passa por cada flat
    @flats.each do |flat|
      # se o id do flat for 205...
      if flat["id"] == params[:id].to_i
        # guarda ele na variavel @flat
        @flat = flat
      end
    end
  end

  def get_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    info = open(url).read
    @flats = JSON.parse(info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/list.html.erb
<h1>List of flats</h1>

<ul>
  <!-- li's com cada flat -->
  <% @flats.each do |flat| %>
    <li> <%= link_to flat['name'], single_path(flat["id"]) %> </li>
  <% end %>
</ul>

app/views/flats/single.html.erb
<h1><%= @flat['name'] %></h1>
<!-- <h2>Price: <%#= "#{@flat['price']} #{@flat['priceCurrency']}" %> </h2> -->
<h2>Price: <%= @flat['price'] %> <%= @flat['priceCurrency'] %> </h2>
<img src="<%= @flat['imageUrl'] %>" height=200>

<p>
  <%= link_to "List Page", list_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>